import type { ShellProfile } from "./types";

const commandStarters = new Set([
  "alias",
  "apt",
  "apt-get",
  "awk",
  "bash",
  "cat",
  "cd",
  "chmod",
  "chown",
  "clear",
  "cmake",
  "code",
  "cp",
  "cargo",
  "curl",
  "df",
  "diff",
  "dnf",
  "docker",
  "docker-compose",
  "du",
  "echo",
  "env",
  "exit",
  "export",
  "find",
  "git",
  "go",
  "grep",
  "head",
  "history",
  "htop",
  "kill",
  "less",
  "ln",
  "ls",
  "make",
  "man",
  "mkdir",
  "more",
  "mv",
  "node",
  "npm",
  "ollama",
  "pacman",
  "ping",
  "pnpm",
  "ps",
  "pwd",
  "python",
  "python3",
  "py",
  "rg",
  "rm",
  "rmdir",
  "rsync",
  "rustup",
  "scp",
  "sed",
  "service",
  "sh",
  "ssh",
  "sudo",
  "systemctl",
  "tail",
  "tar",
  "tauri",
  "top",
  "touch",
  "tree",
  "wc",
  "wget",
  "which",
  "whoami",
  "yarn",
  "yay",
  "zsh",
]);

const commandStarterPrefixes: string[] = [];

const dangerousPatterns: RegExp[] = [
  /\brm\s+(-[a-z]*r[a-z]*f|-[a-z]*f[a-z]*r)\b/i,
  /\brm\s+-rf?\b/i,
  /\bmkfs(\.\w+)?\b/i,
  /\bdd\s+if=/i,
  /\bshutdown\b/i,
  /\breboot\b/i,
  /\bhalt\b/i,
  /\bpoweroff\b/i,
  /\binit\s+0\b/i,
  /\bkill(all)?\s+-9\b/i,
  /\bpkill\b/i,
  /\bgit\s+reset\s+--hard\b/i,
  /\bgit\s+clean\s+-[a-z]*f/i,
  /\b:\s*\(\s*\)\s*\{/, // fork bomb pattern
  /\bchmod\s+-?R?\s*0?777\b/i,
  /\bchown\s+-R\b/i,
  /\b>\s*\/dev\/sd[a-z]/i,
  /\biptables\s+-F\b/i,
];

const cautionPatterns: RegExp[] = [
  /\brm\b/i,
  /\bmv\b/i,
  /\bcp\s+-[a-z]*f/i,
  /\bchmod\b/i,
  /\bchown\b/i,
  /\bsudo\b/i,
  /\bapt(-get)?\s+(install|remove|purge|upgrade|update)\b/i,
  /\bdnf\s+(install|remove|upgrade)\b/i,
  /\bpacman\s+-(S|R|U|Syu)/i,
  /\byay\s+-(S|R)/i,
  /\bsystemctl\s+(start|stop|restart|enable|disable)\b/i,
  /\bservice\s+\w+\s+(start|stop|restart)\b/i,
  /\bcurl\b.*\|\s*(sh|bash)\b/i,
  /\bwget\b.*\|\s*(sh|bash)\b/i,
  /\bgit\s+(clean|checkout|restore|push\s+--force)\b/i,
  /\bnpm\s+(install|uninstall|publish)\b/i,
  /\btar\s+(-)?x[a-z]*f/i,
];

export const bashProfile: ShellProfile = {
  key: "bash",
  displayName: "Bash",
  pathSeparator: "/",
  commandStarters,
  commandStarterPrefixes,
  dangerousPatterns,
  cautionPatterns,
};
