import type { ShellProfile } from "./types";

const commandStarters = new Set([
  "cat",
  "cd",
  "clear",
  "cls",
  "code",
  "copy",
  "cp",
  "cargo",
  "del",
  "dir",
  "docker",
  "docker-compose",
  "echo",
  "exit",
  "git",
  "grep",
  "ls",
  "mkdir",
  "move",
  "mv",
  "node",
  "npm",
  "ollama",
  "pnpm",
  "powershell",
  "pwd",
  "py",
  "python",
  "rm",
  "rmdir",
  "rustup",
  "tauri",
  "type",
  "where",
  "winget",
  "yarn",
]);

const commandStarterPrefixes = [
  "add-",
  "clear-",
  "copy-",
  "get-",
  "move-",
  "new-",
  "remove-",
  "select-",
  "set-",
  "start-",
  "stop-",
  "write-",
];

const dangerousPatterns: RegExp[] = [
  /\brm\b/i,
  /\bremove-item\b/i,
  /\bdel\b/i,
  /\brmdir\b/i,
  /\bformat-volume\b/i,
  /\bformat\b/i,
  /\bshutdown\b/i,
  /\bstop-process\b/i,
  /\btaskkill\b/i,
  /\bgit\s+reset\s+--hard\b/i,
  /\breg\s+(add|delete)\b/i,
];

const cautionPatterns: RegExp[] = [
  /\bmove-item\b/i,
  /\bcopy-item\b/i,
  /\brename-item\b/i,
  /\bgit\s+(clean|checkout|restore)\b/i,
  /\bnew-item\b/i,
  /\bset-content\b/i,
  /\binvoke-webrequest\b/i,
  /\bcurl\b/i,
  /\bwinget\s+install\b/i,
];

export const powershellProfile: ShellProfile = {
  key: "powershell",
  displayName: "PowerShell",
  pathSeparator: "\\",
  commandStarters,
  commandStarterPrefixes,
  dangerousPatterns,
  cautionPatterns,
};
