import type { ShellProfile } from "./types";

const commandStarters = new Set([
  "alias",
  "awk",
  "bash",
  "brew",
  "cat",
  "cd",
  "chmod",
  "chown",
  "clear",
  "cp",
  "cargo",
  "curl",
  "defaults",
  "df",
  "diff",
  "docker",
  "du",
  "echo",
  "env",
  "exit",
  "export",
  "find",
  "git",
  "grep",
  "head",
  "history",
  "kill",
  "less",
  "ln",
  "ls",
  "make",
  "man",
  "mkdir",
  "mv",
  "node",
  "npm",
  "ollama",
  "open",
  "pbcopy",
  "pbpaste",
  "ping",
  "pnpm",
  "ps",
  "pwd",
  "python",
  "python3",
  "rg",
  "rm",
  "rmdir",
  "rsync",
  "rustup",
  "sed",
  "sh",
  "ssh",
  "sudo",
  "sw_vers",
  "tail",
  "tar",
  "touch",
  "uname",
  "which",
  "whoami",
  "xcodebuild",
  "yarn",
  "zsh",
]);

const commandStarterPrefixes: string[] = [];

const dangerousPatterns: RegExp[] = [
  /\brm\s+(-[a-z]*r[a-z]*f|-[a-z]*f[a-z]*r)\b/i,
  /\brm\s+-rf?\b/i,
  /\bdiskutil\s+erase(disk|volume)\b/i,
  /\bdd\s+if=/i,
  /\bshutdown\b/i,
  /\breboot\b/i,
  /\bhalt\b/i,
  /\bkill(all)?\s+-9\b/i,
  /\bpkill\b/i,
  /\bgit\s+reset\s+--hard\b/i,
  /\bgit\s+clean\s+-[a-z]*f/i,
  /\b:\s*\(\s*\)\s*\{/, // fork bomb pattern
  /\bchmod\s+-?R?\s*0?777\b/i,
  /\bchown\s+-R\b/i,
  /\b>\s*\/dev\/disk\d+/i,
];

const cautionPatterns: RegExp[] = [
  /\brm\b/i,
  /\bmv\b/i,
  /\bcp\s+-[a-z]*f/i,
  /\bchmod\b/i,
  /\bchown\b/i,
  /\bsudo\b/i,
  /\bbrew\s+(install|uninstall|upgrade)\b/i,
  /\bcurl\b.*\|\s*(sh|bash|zsh)\b/i,
  /\bgit\s+(clean|checkout|restore|push\s+--force)\b/i,
  /\bnpm\s+(install|uninstall|publish)\b/i,
  /\btar\s+(-)?x[a-z]*f/i,
];

export const zshProfile: ShellProfile = {
  key: "zsh",
  displayName: "Zsh",
  pathSeparator: "/",
  commandStarters,
  commandStarterPrefixes,
  dangerousPatterns,
  cautionPatterns,
};
